version: '3'

networks:
  backend:
    driver: bridge

volumes:
  ### ignore folder volume #####
  var:
    driver: local
  vendor:
    driver: local
  node_modules:
    driver: local
  pg-database:
    driver: local

services:
  ec-cube:
    build:
      context: .
    environment:
      DATABASE_URL: "postgres://dbuser:secret@postgres/eccubedb"
      DATABASE_SERVER_VERSION: 14
    ports:
      - 8080:80
      - 4430:443
    volumes:
      ### 同期対象からコストの重いフォルダを除外 #####################
      - "var:/var/www/html/var"
      - "vendor:/var/www/html/vendor"
      - "node_modules:/var/www/html/node_modules"
    networks:
      - backend

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: eccubedb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secret
    ports:
      - 15432:5432
    volumes:
      - pg-database:/var/lib/postgresql/data
    networks:
      - backend
